language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libsndfile1 libsndfile-dev libasound2-dev
install:
  - pip install -r requirements.txt --no-deps
  - python manage.py migrate
script:
  - python manage.py test api