language: python
python:
  - "3.7"
install:
  - apt install libsndfile1 libsndfile-dev libasound2-dev
  - pip install -r requirements.txt --no-deps
  - python manage.py migrate
script:
  - python manage.py test api