# Generated by Django 2.2.6 on 2019-10-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(choices=[('short', 'short'), ('medium', 'medium'), ('long', 'long')], max_length=250),
        ),
    ]
