# Generated by Django 2.2.6 on 2019-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191030_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=250),
        ),
    ]
