# Generated by Django 2.2.7 on 2019-12-07 17:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191031_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songstat',
            name='created_at',
            field=models.DateTimeField(blank=True, default=api.models.current_time_with_utc_timezone),
        ),
    ]
