name: Django application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update apt dependencies
      run: |
        sudo apt-get update
    - name: Install apt dependencies
      run: |
        sudo apt-get install libsndfile1 libsndfile-dev libasound2-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-deps
    - name: Make migrations
      run: |
        python manage.py migrate
    - name: Test with django test
      run: |
        python manage.py test api
